### ISSUE TITLE
Fastest nodejs option - HyperExpress

### ISSUE THREAD

**Issue by dougg0k** [denosaurs/bench#33]
Hi, can you add this library? https://github.com/kartikk221/hyper-express

https://github.com/kartikk221/hyper-express/blob/master/docs/Benchmarks.md

**Comment by eliassjogreen** [comment]
Sure, it is quite simple to implement a new framework. I am not sure I have the time to do so at the moment, but you are welcome to submit a PR or simply wait.

**Comment by dougg0k** [comment]
Done https://github.com/denosaurs/bench/pull/52
