### ISSUE TITLE
`autocannon` is too slow to benchmark Deno or Bun correctly

### ISSUE THREAD

**Issue by Jarred-Sumner** [denosaurs/bench#41]
For many of the results on the homepage, you are benchmarking `autocannon`. When the HTTP client is slower than the HTTP server, you are benchmarking the HTTP client. That's why the numbers get so close towards the top -- they're within the margin of error for `autocannon`.

Deno and Bun's numbers will be more accurate (higher) using a tool that is better at keeping up. `wrk` is also not quite fast enough.

[`oha`](https://github.com/hatoo/oha) would be a more accurate choice, though [`http_load_test`](https://github.com/uNetworking/uSockets/blob/4528c2f9dd686a27aa644911434d1da3b6312236/examples/http_load_test.c) would be best.

**Comment by eliassjogreen** [comment]
Interesting! I tried to use a package called Bombardier but reverted back to autocannon because it provided better json output. I initially wanted to use Oha but that does not to my knowledge output json or any other machine-readable format?

**Comment by NightScript370** [comment]
Since the PR was reverted, could we reopen this issue?
