### ISSUE TITLE
More complex benchmarks?

### ISSUE THREAD

**Issue by hronro** [denosaurs/bench#64]
Just responding in plain text "Hello, Bench!" is meaningless in real-world scenarios.

Please considering add some more complex scenarios like parsing query strings, parsing cookies, parsing JSON from request bodies, serializing JSON to response bodies, or even interacting with databases.

**Comment by boywithkeyboard** [comment]
~~@hronro I'll work on a rewrite of this repository in the upcoming weeks which should solve your issue.~~

**Comment by hronro** [comment]
Any reason for closing this?
