### ISSUE TITLE
Bun is roughly 2x faster than deno

### ISSUE THREAD

**Issue by aquapi** [denosaurs/bench#85]
Add another column for average requests per second all frameworks can handle

**Comment by boywithkeyboard** [comment]
What do you mean? Didn't we already list this data?

![image](https://github.com/denosaurs/bench/assets/62482066/592f5933-9827-452a-a223-7fdcd5e63dfb)

**Comment by aquapi** [comment]
Bun is roughly 2x faster than Deno

**Comment by aquapi** [comment]
Something is not right here

**Comment by aquapi** [comment]
You can try another benchmarking tool and see how it performs, for instance:
- bombardier with fast http enabled
- http-load-test from uWebSockets repo

**Comment by boywithkeyboard** [comment]
@aquapi, please open a new issue and don't edit your original post!
